## Extract Data

In [2]:
import requests

In [3]:
url = "https://api.openweathermap.org/data/2.5/weather"

params = {
    "appid": "6a13e61e853763292101962a026aa3e8",
    "q": "Cairo"
}

response = requests.get(url, params=params)

data = response.json()

In [4]:
data

{'coord': {'lon': 31.2497, 'lat': 30.0626},
 'weather': [{'id': 800,
   'main': 'Clear',
   'description': 'clear sky',
   'icon': '01n'}],
 'base': 'stations',
 'main': {'temp': 296.57,
  'feels_like': 296.43,
  'temp_min': 296.16,
  'temp_max': 296.57,
  'pressure': 1016,
  'humidity': 56,
  'sea_level': 1016,
  'grnd_level': 1016},
 'visibility': 10000,
 'wind': {'speed': 4.12, 'deg': 360},
 'clouds': {'all': 0},
 'dt': 1790804535,
 'sys': {'type': 1,
  'id': 2514,
  'country': 'EG',
  'sunrise': 1790826484,
  'sunset': 1790869277},
 'timezone': 10800,
 'id': 360630,
 'name': 'Cairo',
 'cod': 200}

In [5]:
list_cities = []

In [6]:
cities = [
    "Cairo",
    "Giza",
    "Alexandria",
    "Port Said",
    "Suez",
    "Ismailia",
    "Mansoura",
    "Tanta",
    "Luxor",
    "Aswan"
]

In [7]:
url = "https://api.openweathermap.org/data/2.5/weather"

params = {
    "appid": "6a13e61e853763292101962a026aa3e8",
    "q": "city"
}

for city in cities:
    params["q"] = city
    response = requests.get(url, params=params)
    data = response.json()
    list_cities.append(data)

In [8]:
list_cities

[{'coord': {'lon': 31.2497, 'lat': 30.0626},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'base': 'stations',
  'main': {'temp': 296.57,
   'feels_like': 296.43,
   'temp_min': 296.16,
   'temp_max': 296.57,
   'pressure': 1016,
   'humidity': 56,
   'sea_level': 1016,
   'grnd_level': 1016},
  'visibility': 10000,
  'wind': {'speed': 4.12, 'deg': 360},
  'clouds': {'all': 0},
  'dt': 1790804535,
  'sys': {'type': 1,
   'id': 2514,
   'country': 'EG',
   'sunrise': 1790826484,
   'sunset': 1790869277},
  'timezone': 10800,
  'id': 360630,
  'name': 'Cairo',
  'cod': 200},
 {'coord': {'lon': 31.2109, 'lat': 30.0081},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'base': 'stations',
  'main': {'temp': 296.56,
   'feels_like': 296.42,
   'temp_min': 296.15,
   'temp_max': 296.56,
   'pressure': 1016,
   'humidity': 56,
   'sea_level': 1016,
   'grnd_level': 1014},
  'visibility': 10000,
  'wind': {'speed': 1.55, 'deg': 4, 'gust': 3.04},
  'clouds': {'all': 0},
  'dt': 1790804583,
  'sys': {'type': 1,
   'id': 2514,
   'country': 'EG',
   'sunrise': 1790826493,
   'sunset': 1790869288},
  'timezone': 10800,
  'id': 360995,
  'name': 'Giza',
  'cod': 200},
 {'coord': {'lon': 29.9553, 'lat': 31.2156},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'base': 'stations',
  'main': {'temp': 294.13,
   'feels_like': 294.06,
   'temp_min': 294.13,
   'temp_max': 294.13,
   'pressure': 1016,
   'humidity': 68,
   'sea_level': 1016,
   'grnd_level': 1016},
  'visibility': 10000,
  'wind': {'speed': 2.06, 'deg': 150},
  'clouds': {'all': 6},
  'dt': 1790804583,
  'sys': {'type': 1,
   'id': 2511,
   'country': 'EG',
   'sunrise': 1790826812,
   'sunset': 1790869570},
  'timezone': 10800,
  'id': 361058,
  'name': 'Alexandria',
  'cod': 200},
 {'coord': {'lon': 32.2841, 'lat': 31.2565},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'base': 'stations',
  'main': {'temp': 298.14,
   'feels_like': 298.18,
   'temp_min': 298.14,
   'temp_max': 298.14,
   'pressure': 1016,
   'humidity': 57,
   'sea_level': 1016,
   'grnd_level': 1016},
  'visibility': 10000,
  'wind': {'speed': 4.63, 'deg': 290},
  'clouds': {'all': 9},
  'dt': 1790804912,
  'sys': {'type': 1,
   'id': 2522,
   'country': 'EG',
   'sunrise': 1790826254,
   'sunset': 1790869011},
  'timezone': 10800,
  'id': 358619,
  'name': 'Port Said',
  'cod': 200},
 {'coord': {'lon': 32.5263, 'lat': 29.9737},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'base': 'stations',
  'main': {'temp': 295.29,
   'feels_like': 295.44,
   'temp_min': 295.29,
   'temp_max': 295.29,
   'pressure': 1016,
   'humidity': 72,
   'sea_level': 1016,
   'grnd_level': 1007},
  'visibility': 10000,
  'wind': {'speed': 2.04, 'deg': 320, 'gust': 3.89},
  'clouds': {'all': 0},
  'dt': 1790804913,
  'sys': {'country': 'EG', 'sunrise': 1790826176, 'sunset': 1790868973},
  'timezone': 10800,
  'id': 359796,
  'name': 'Suez',
  'cod': 200},
 {'coord': {'lon': 32.2723, 'lat': 30.6043},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'base': 'stations',
  'main': {'temp': 295.4,
   'feels_like': 295.48,
   'temp_min': 295.4,
   'temp_max': 295.4,
   'pressure': 1016,
   'humidity': 69,
   'sea_level': 1016,
   'grnd_level': 1015},
  'visibility': 10000,
  'wind': {'speed': 0.77, 'deg': 310, 'gust': 1.07},
  'clouds': {'all': 1},
  'dt': 1790804763,
  'sys': {'country': 'EG', 'sunrise': 1790826247, 'sunset': 1790869024},
  'timezone': 10800,
  'id': 361055,
  'name': 'Ismailia',
  'cod': 200},
 {'coord': {'lon': -1.3394, 'lat': 34.8616},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'base': 'stations',
  'main': {'temp': 290.94,
   'feels_like': 290.94,
   'temp_min': 290.94,
   'temp_max': 290.94,
   'pressure': 1020,
   'humidity': 83,
   'sea_level': 1020,
   'grnd_level': 959},
  'visibility': 10000,
  'wind': {'speed': 2.06, 'deg': 50},
  'clouds': {'all': 42},
  'dt': 1790804764,
  'sys': {'type': 1,
   'id': 1091,
   'country': 'DZ',
   'sunrise': 1790747940,
   'sunset': 1790790701},
  'timezone': 3600,
  'id': 2490183,
  'name': 'Mansoûra',
  'cod': 200},
 {'coord': {'lon': 31.0019, 'lat': 30.7885},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'base': 'stations',
  'main': {'temp': 295.12,
   'feels_like': 295.2,
   'temp_min': 295.12,
   'temp_max': 295.12,
   'pressure': 1016,
   'humidity': 70,
   'sea_level': 1016,
   'grnd_level': 1015},
  'visibility': 10000,
  'wind': {'speed': 1.02, 'deg': 281, 'gust': 1.4},
  'clouds': {'all': 2},
  'dt': 1790804583,
  'sys': {'country': 'EG', 'sunrise': 1790826555, 'sunset': 1790869326},
  'timezone': 10800,
  'id': 347497,
  'name': 'Tanta',
  'cod': 200},
 {'coord': {'lon': 32.6421, 'lat': 25.6989},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'base': 'stations',
  'main': {'temp': 301.18,
   'feels_like': 300.47,
   'temp_min': 301.18,
   'temp_max': 301.18,
   'pressure': 1014,
   'humidity': 34,
   'sea_level': 1014,
   'grnd_level': 990},
  'visibility': 10000,
  'wind': {'speed': 0, 'deg': 0},
  'clouds': {'all': 0},
  'dt': 1790804560,
  'sys': {'type': 1,
   'id': 2516,
   'country': 'EG',
   'sunrise': 1790826086,
   'sunset': 1790869008},
  'timezone': 10800,
  'id': 360502,
  'name': 'Luxor',
  'cod': 200},
 {'coord': {'lon': 32.907, 'lat': 24.0934},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'base': 'stations',
  'main': {'temp': 303.76,
   'feels_like': 302.49,
   'temp_min': 303.76,
   'temp_max': 303.76,
   'pressure': 1013,
   'humidity': 30,
   'sea_level': 1013,
   'grnd_level': 994},
  'visibility': 10000,
  'wind': {'speed': 5.14, 'deg': 350},
  'clouds': {'all': 0},
  'dt': 1790804644,
  'sys': {'type': 1,
   'id': 2526,
   'country': 'EG',
   'sunrise': 1790826000,
   'sunset': 1790868967},
  'timezone': 10800,
  'id': 359792,
  'name': 'Aswān',
  'cod': 200}]

In [9]:
list_cities[0]

{'coord': {'lon': 31.2497, 'lat': 30.0626},
 'weather': [{'id': 800,
   'main': 'Clear',
   'description': 'clear sky',
   'icon': '01n'}],
 'base': 'stations',
 'main': {'temp': 296.57,
  'feels_like': 296.43,
  'temp_min': 296.16,
  'temp_max': 296.57,
  'pressure': 1016,
  'humidity': 56,
  'sea_level': 1016,
  'grnd_level': 1016},
 'visibility': 10000,
 'wind': {'speed': 4.12, 'deg': 360},
 'clouds': {'all': 0},
 'dt': 1790804535,
 'sys': {'type': 1,
  'id': 2514,
  'country': 'EG',
  'sunrise': 1790826484,
  'sunset': 1790869277},
 'timezone': 10800,
 'id': 360630,
 'name': 'Cairo',
 'cod': 200}

In [10]:
list_cities[0]['main']['temp']

296.57

In [11]:
new_temp = []

for i in list_cities:
    temp = i['main']['temp'] - 273
    new_temp.append([round(temp,2)])

In [12]:
new_temp

[[23.57],
 [23.56],
 [21.13],
 [25.14],
 [22.29],
 [22.4],
 [17.94],
 [22.12],
 [28.18],
 [30.76]]

In [13]:
list_cities[0]

{'coord': {'lon': 31.2497, 'lat': 30.0626},
 'weather': [{'id': 800,
   'main': 'Clear',
   'description': 'clear sky',
   'icon': '01n'}],
 'base': 'stations',
 'main': {'temp': 296.57,
  'feels_like': 296.43,
  'temp_min': 296.16,
  'temp_max': 296.57,
  'pressure': 1016,
  'humidity': 56,
  'sea_level': 1016,
  'grnd_level': 1016},
 'visibility': 10000,
 'wind': {'speed': 4.12, 'deg': 360},
 'clouds': {'all': 0},
 'dt': 1790804535,
 'sys': {'type': 1,
  'id': 2514,
  'country': 'EG',
  'sunrise': 1790826484,
  'sunset': 1790869277},
 'timezone': 10800,
 'id': 360630,
 'name': 'Cairo',
 'cod': 200}

In [14]:
data['wind']['speed']

5.14

In [15]:
data['weather']

[{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}]

In [16]:
city = 'Alexandria'
country = 'Egypt'
latitude  =  data['coord']['lat']
longitude  =  data['coord']['lon']
tempreature = data['main']['temp'] - 273
pressure = data['main']['pressure']
Humidity = data['main']['humidity']
wind_speed = data['wind']['speed']
WeatherMain = data['weather'][0]['main']
weather_description = data['weather'][0]['description']


city, country, latitude, longitude, tempreature, pressure, Humidity, wind_speed, WeatherMain, weather_description

('Alexandria',
 'Egypt',
 24.0934,
 32.907,
 30.75999999999999,
 1013,
 30,
 5.14,
 'Clear',
 'clear sky')

In [17]:
list_cities = [] 

url = "https://api.openweathermap.org/data/2.5/weather"

params = {
    "appid": "6a13e61e853763292101962a026aa3e8",
    "q": "city"
}

for city in cities:
    params["q"] = city
    response = requests.get(url, params=params)
    data = response.json()
    
    city = city
    country = 'Egypt'
    latitude  =  data['coord']['lat']
    longitude  =  data['coord']['lon']
    tempreature = data['main']['temp'] - 273
    pressure = data['main']['pressure']
    Humidity = data['main']['humidity']
    wind_speed = data['wind']['speed']
    WeatherMain = data['weather'][0]['main']
    weather_description = data['weather'][0]['description']

    list_cities.append([city, country, latitude, longitude, tempreature, pressure, Humidity, wind_speed, WeatherMain, weather_description])

In [18]:
list_cities

[['Cairo',
  'Egypt',
  30.0626,
  31.2497,
  23.569999999999993,
  1016,
  56,
  4.12,
  'Clear',
  'clear sky'],
 ['Giza',
  'Egypt',
  30.0081,
  31.2109,
  23.560000000000002,
  1016,
  56,
  1.55,
  'Clear',
  'clear sky'],
 ['Alexandria',
  'Egypt',
  31.2156,
  29.9553,
  21.129999999999995,
  1016,
  68,
  2.06,
  'Clear',
  'clear sky'],
 ['Port Said',
  'Egypt',
  31.2565,
  32.2841,
  25.139999999999986,
  1016,
  57,
  4.63,
  'Clear',
  'clear sky'],
 ['Suez',
  'Egypt',
  29.9737,
  32.5263,
  22.29000000000002,
  1016,
  72,
  2.04,
  'Clear',
  'clear sky'],
 ['Ismailia',
  'Egypt',
  30.6043,
  32.2723,
  22.399999999999977,
  1016,
  69,
  0.77,
  'Clear',
  'clear sky'],
 ['Mansoura',
  'Egypt',
  34.8616,
  -1.3394,
  17.939999999999998,
  1020,
  83,
  2.06,
  'Clouds',
  'scattered clouds'],
 ['Tanta',
  'Egypt',
  30.7885,
  31.0019,
  22.120000000000005,
  1016,
  70,
  1.02,
  'Clear',
  'clear sky'],
 ['Luxor',
  'Egypt',
  25.6989,
  32.6421,
  28.180000000000007,
  1014,
  34,
  0,
  'Clear',
  'clear sky'],
 ['Aswan',
  'Egypt',
  24.0934,
  32.907,
  30.75999999999999,
  1013,
  30,
  5.14,
  'Clear',
  'clear sky']]

In [19]:
print(type(list_cities))
print(type(list_cities[0]))
print(list_cities[0])

<class 'list'>
<class 'list'>
['Cairo', 'Egypt', 30.0626, 31.2497, 23.569999999999993, 1016, 56, 4.12, 'Clear', 'clear sky']

In [20]:
import pandas as pd
df = pd.DataFrame(list_cities, columns=['City', 'Country', 'Latitude', 'Longitude', 'Temperature', 'Pressure', 'Humidity', 'Wind Speed', 'Weather Main', 'Weather Description'])

In [21]:
df

,City,Country,Latitude,Longitude,Temperature,Pressure,Humidity,Wind Speed,Weather Main,Weather Description
0,Cairo,Egypt,30.0626,31.2497,23.57,1016,56,4.12,Clear,clear sky
1,Giza,Egypt,30.0081,31.2109,23.56,1016,56,1.55,Clear,clear sky
2,Alexandria,Egypt,31.2156,29.9553,21.13,1016,68,2.06,Clear,clear sky
3,Port Said,Egypt,31.2565,32.2841,25.14,1016,57,4.63,Clear,clear sky
4,Suez,Egypt,29.9737,32.5263,22.29,1016,72,2.04,Clear,clear sky
5,Ismailia,Egypt,30.6043,32.2723,22.40,1016,69,0.77,Clear,clear sky
6,Mansoura,Egypt,34.8616,-1.3394,17.94,1020,83,2.06,Clouds,scattered clouds
7,Tanta,Egypt,30.7885,31.0019,22.12,1016,70,1.02,Clear,clear sky
8,Luxor,Egypt,25.6989,32.6421,28.18,1014,34,0.00,Clear,clear sky
9,Aswan,Egypt,24.0934,32.9070,30.76,1013,30,5.14,Clear,clear sky

In [22]:
def fun1(city):
    if city in ['Luxor','Aswan']:
        return 'Lower'
    else:
        return 'Upper'

In [23]:
df['Region'] = df['City'].apply(fun1)

In [24]:
df

,City,Country,Latitude,Longitude,Temperature,Pressure,Humidity,Wind Speed,Weather Main,Weather Description,Region
0,Cairo,Egypt,30.0626,31.2497,23.57,1016,56,4.12,Clear,clear sky,Upper
1,Giza,Egypt,30.0081,31.2109,23.56,1016,56,1.55,Clear,clear sky,Upper
2,Alexandria,Egypt,31.2156,29.9553,21.13,1016,68,2.06,Clear,clear sky,Upper
3,Port Said,Egypt,31.2565,32.2841,25.14,1016,57,4.63,Clear,clear sky,Upper
4,Suez,Egypt,29.9737,32.5263,22.29,1016,72,2.04,Clear,clear sky,Upper
5,Ismailia,Egypt,30.6043,32.2723,22.40,1016,69,0.77,Clear,clear sky,Upper
6,Mansoura,Egypt,34.8616,-1.3394,17.94,1020,83,2.06,Clouds,scattered clouds,Upper
7,Tanta,Egypt,30.7885,31.0019,22.12,1016,70,1.02,Clear,clear sky,Upper
8,Luxor,Egypt,25.6989,32.6421,28.18,1014,34,0.00,Clear,clear sky,Lower
9,Aswan,Egypt,24.0934,32.9070,30.76,1013,30,5.14,Clear,clear sky,Lower

In [25]:
def tempCategory(temp):
    if temp < 20:
        return 'Cold'
    elif temp >= 20 and temp < 30:
        return 'Moderate'
    else:
        return 'Hot'

In [26]:
df['Temperature Category'] = df['Temperature'].apply(tempCategory)

In [27]:
def HumidityCategory(humidity):
    if humidity < 30:
        return 'Low'
    elif humidity >= 30 and humidity < 60:
        return 'Moderate'
    else:
        return 'High'

In [28]:
df['Humidity Category'] = df['Humidity'].apply(HumidityCategory)

In [29]:
df

,City,Country,Latitude,Longitude,Temperature,Pressure,Humidity,Wind Speed,Weather Main,Weather Description,Region,Temperature Category,Humidity Category
0,Cairo,Egypt,30.0626,31.2497,23.57,1016,56,4.12,Clear,clear sky,Upper,Moderate,Moderate
1,Giza,Egypt,30.0081,31.2109,23.56,1016,56,1.55,Clear,clear sky,Upper,Moderate,Moderate
2,Alexandria,Egypt,31.2156,29.9553,21.13,1016,68,2.06,Clear,clear sky,Upper,Moderate,High
3,Port Said,Egypt,31.2565,32.2841,25.14,1016,57,4.63,Clear,clear sky,Upper,Moderate,Moderate
4,Suez,Egypt,29.9737,32.5263,22.29,1016,72,2.04,Clear,clear sky,Upper,Moderate,High
5,Ismailia,Egypt,30.6043,32.2723,22.40,1016,69,0.77,Clear,clear sky,Upper,Moderate,High
6,Mansoura,Egypt,34.8616,-1.3394,17.94,1020,83,2.06,Clouds,scattered clouds,Upper,Cold,High
7,Tanta,Egypt,30.7885,31.0019,22.12,1016,70,1.02,Clear,clear sky,Upper,Moderate,High
8,Luxor,Egypt,25.6989,32.6421,28.18,1014,34,0.00,Clear,clear sky,Lower,Moderate,Moderate
9,Aswan,Egypt,24.0934,32.9070,30.76,1013,30,5.14,Clear,clear sky,Lower,Hot,Moderate

In [30]:
import datetime
date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(date)

2026-10-01 00:48:51

In [31]:
df['Ingestion Date'] = date

In [32]:
df

,City,Country,Latitude,Longitude,Temperature,Pressure,Humidity,Wind Speed,Weather Main,Weather Description,Region,Temperature Category,Humidity Category,Ingestion Date
0,Cairo,Egypt,30.0626,31.2497,23.57,1016,56,4.12,Clear,clear sky,Upper,Moderate,Moderate,2026-10-01 00:48:51
1,Giza,Egypt,30.0081,31.2109,23.56,1016,56,1.55,Clear,clear sky,Upper,Moderate,Moderate,2026-10-01 00:48:51
2,Alexandria,Egypt,31.2156,29.9553,21.13,1016,68,2.06,Clear,clear sky,Upper,Moderate,High,2026-10-01 00:48:51
3,Port Said,Egypt,31.2565,32.2841,25.14,1016,57,4.63,Clear,clear sky,Upper,Moderate,Moderate,2026-10-01 00:48:51
4,Suez,Egypt,29.9737,32.5263,22.29,1016,72,2.04,Clear,clear sky,Upper,Moderate,High,2026-10-01 00:48:51
5,Ismailia,Egypt,30.6043,32.2723,22.40,1016,69,0.77,Clear,clear sky,Upper,Moderate,High,2026-10-01 00:48:51
6,Mansoura,Egypt,34.8616,-1.3394,17.94,1020,83,2.06,Clouds,scattered clouds,Upper,Cold,High,2026-10-01 00:48:51
7,Tanta,Egypt,30.7885,31.0019,22.12,1016,70,1.02,Clear,clear sky,Upper,Moderate,High,2026-10-01 00:48:51
8,Luxor,Egypt,25.6989,32.6421,28.18,1014,34,0.00,Clear,clear sky,Lower,Moderate,Moderate,2026-10-01 00:48:51
9,Aswan,Egypt,24.0934,32.9070,30.76,1013,30,5.14,Clear,clear sky,Lower,Hot,Moderate,2026-10-01 00:48:51

### Load Data

In [33]:
data = list(df.itertuples(index = None, name = None))

In [34]:
data

[('Cairo',
  'Egypt',
  30.0626,
  31.2497,
  23.569999999999993,
  1016,
  56,
  4.12,
  'Clear',
  'clear sky',
  'Upper',
  'Moderate',
  'Moderate',
  '2026-10-01 00:48:51'),
 ('Giza',
  'Egypt',
  30.0081,
  31.2109,
  23.560000000000002,
  1016,
  56,
  1.55,
  'Clear',
  'clear sky',
  'Upper',
  'Moderate',
  'Moderate',
  '2026-10-01 00:48:51'),
 ('Alexandria',
  'Egypt',
  31.2156,
  29.9553,
  21.129999999999995,
  1016,
  68,
  2.06,
  'Clear',
  'clear sky',
  'Upper',
  'Moderate',
  'High',
  '2026-10-01 00:48:51'),
 ('Port Said',
  'Egypt',
  31.2565,
  32.2841,
  25.139999999999986,
  1016,
  57,
  4.63,
  'Clear',
  'clear sky',
  'Upper',
  'Moderate',
  'Moderate',
  '2026-10-01 00:48:51'),
 ('Suez',
  'Egypt',
  29.9737,
  32.5263,
  22.29000000000002,
  1016,
  72,
  2.04,
  'Clear',
  'clear sky',
  'Upper',
  'Moderate',
  'High',
  '2026-10-01 00:48:51'),
 ('Ismailia',
  'Egypt',
  30.6043,
  32.2723,
  22.399999999999977,
  1016,
  69,
  0.77,
  'Clear',
  'clear sky',
  'Upper',
  'Moderate',
  'High',
  '2026-10-01 00:48:51'),
 ('Mansoura',
  'Egypt',
  34.8616,
  -1.3394,
  17.939999999999998,
  1020,
  83,
  2.06,
  'Clouds',
  'scattered clouds',
  'Upper',
  'Cold',
  'High',
  '2026-10-01 00:48:51'),
 ('Tanta',
  'Egypt',
  30.7885,
  31.0019,
  22.120000000000005,
  1016,
  70,
  1.02,
  'Clear',
  'clear sky',
  'Upper',
  'Moderate',
  'High',
  '2026-10-01 00:48:51'),
 ('Luxor',
  'Egypt',
  25.6989,
  32.6421,
  28.180000000000007,
  1014,
  34,
  0.0,
  'Clear',
  'clear sky',
  'Lower',
  'Moderate',
  'Moderate',
  '2026-10-01 00:48:51'),
 ('Aswan',
  'Egypt',
  24.0934,
  32.907,
  30.75999999999999,
  1013,
  30,
  5.14,
  'Clear',
  'clear sky',
  'Lower',
  'Hot',
  'Moderate',
  '2026-10-01 00:48:51')]

In [35]:
print(len(data))

10

In [37]:
import pyodbc
conn = pyodbc.connect(                    
    "driver={ODBC Driver 17 for SQL Server};"
    "server=localhost;"
    "database=task;"
    "Trusted_Connection=yes;"
)
 
curosr = conn.cursor()
curosr.execute('''create table KareemEmara(   
    city varchar(50),
    country varchar(50),
    latitude varchar(50),
    longitude varchar(50),
    tempreature varchar(50),
    pressure varchar(50),
    Humidity varchar(50),
    wind_speed varchar(50),
    WeatherMain varchar(50),
    weather_description varchar(50),
    Region varchar(50),
    Temperature_Category varchar(50),
    Humidity_Category varchar(50),
    Ingestion_Date varchar(50))    
    ''')
 
curosr.close()
 
conn.commit()
conn.close()

In [ ]:
# SQL Server
import pyodbc
conn = pyodbc.connect(                    
    "driver={ODBC Driver 17 for SQL Server};"
    "server=depi12462.database.windows.net;"
    "database=Depi;"
    "UID=sqladmin;"
    "PWD=Depi123#;"
)

curosr = conn.cursor()
curosr.executemany('''insert into KareemEmara values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)''', data)

curosr.close()
 
conn.commit()
conn.close()

In [ ]:
# localhost
import pyodbc
conn = pyodbc.connect(                    
    "driver={ODBC Driver 17 for SQL Server};"
    "server=localhost;"
    "database=task;"
    "Trusted_Connection=yes;"
)
 
curosr = conn.cursor()
curosr.executemany('''insert into KareemEmara values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)''', data)

curosr.close()
 
conn.commit()
conn.close()

In [40]:
import pyodbc
conn = pyodbc.connect(                    
    "driver={ODBC Driver 17 for SQL Server};"
    "server=localhost;"
    "database=task;"
    "Trusted_Connection=yes;"
)
 
df = pd.read_sql_query('select * from KareemEmara', conn)
df

C:\Users\pc\AppData\Local\Temp\ipykernel_39276\2274253783.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query('select * from KareemEmara', conn)

,city,country,latitude,longitude,tempreature,pressure,Humidity,wind_speed,WeatherMain,weather_description,Region,Temperature_Category,Humidity_Category,Ingestion_Date
0,Cairo,Egypt,30.0626,31.2497,23.57,1016,56,4.12,Clear,clear sky,Upper,Moderate,Moderate,2026-10-01 00:48:51
1,Giza,Egypt,30.0081,31.2109,23.56,1016,56,1.55,Clear,clear sky,Upper,Moderate,Moderate,2026-10-01 00:48:51
2,Alexandria,Egypt,31.2156,29.9553,21.13,1016,68,2.06,Clear,clear sky,Upper,Moderate,High,2026-10-01 00:48:51
3,Port Said,Egypt,31.2565,32.2841,25.14,1016,57,4.63,Clear,clear sky,Upper,Moderate,Moderate,2026-10-01 00:48:51
4,Suez,Egypt,29.9737,32.5263,22.29,1016,72,2.04,Clear,clear sky,Upper,Moderate,High,2026-10-01 00:48:51
5,Ismailia,Egypt,30.6043,32.2723,22.4,1016,69,0.77,Clear,clear sky,Upper,Moderate,High,2026-10-01 00:48:51
6,Mansoura,Egypt,34.8616,-1.3394,17.94,1020,83,2.06,Clouds,scattered clouds,Upper,Cold,High,2026-10-01 00:48:51
7,Tanta,Egypt,30.7885,31.0019,22.12,1016,70,1.02,Clear,clear sky,Upper,Moderate,High,2026-10-01 00:48:51
8,Luxor,Egypt,25.6989,32.6421,28.18,1014,34,0,Clear,clear sky,Lower,Moderate,Moderate,2026-10-01 00:48:51
9,Aswan,Egypt,24.0934,32.907,30.76,1013,30,5.14,Clear,clear sky,Lower,Hot,Moderate,2026-10-01 00:48:51